# Generated by Django 5.0.2 on 2024-03-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sueldo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
