# Generated by Django 5.0.2 on 2024-03-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
