# Generated by Django 5.0.2 on 2024-03-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_rename_categoria_producto_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(max_length=50),
        ),
    ]
