# Generated by Django 5.0.2 on 2024-03-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_alter_empleado_dni_alter_producto_precio_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.IntegerField(),
        ),
    ]
