# Generated by Django 5.0.2 on 2024-03-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
