# Generated by Django 5.0.2 on 2024-04-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplicacion", "0012_alter_cliente_dni"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="dni",
            field=models.IntegerField(),
        ),
    ]
