# Generated by Django 5.0.2 on 2024-08-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplicacion", "0016_order_alter_producto_nombre_order_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="cantidad",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
