# Generated by Django 5.0.2 on 2024-08-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplicacion", "0017_producto_cantidad_producto_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="cantidad",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.CharField(max_length=200),
        ),
    ]
