# Generated by Django 5.0.2 on 2024-08-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplicacion", "0018_alter_producto_cantidad_alter_producto_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="cantidad",
            field=models.IntegerField(default=0),
        ),
    ]
