# Generated by Django 5.0.2 on 2024-08-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplicacion", "0020_remove_order_detail_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="cliente",
            field=models.CharField(max_length=50),
        ),
    ]
