# Generated by Django 5.0.2 on 2024-08-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplicacion", "0022_pedidodetalle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="cantidad",
        ),
        migrations.AlterField(
            model_name="pedido",
            name="direccion",
            field=models.CharField(max_length=100),
        ),
    ]
